// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxdhoukjeayrxfdqvknq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4ZGhvdWtqZWF5cnhmZHF2a25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MDc0MzksImV4cCI6MjA4OTQ4MzQzOX0.Co0L2wLKUswzcElSgkYz1VCSKjILunzpPUWoI27IZNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});